# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171118_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
