# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
