# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='editor',
            new_name='user',
        ),
    ]
